<?php
/** One-time polish of existing Elementor reference layout to v2. */
if(!defined('ABSPATH')) exit;
function x13walk(&$els,$cb){foreach($els as &$e){$cb($e);if(!empty($e['elements'])&&is_array($e['elements']))x13walk($e['elements'],$cb);}unset($e);}
add_action('init',function(){
 if(!isset($_GET['x13_polish_v2'])||'1'!==(string)$_GET['x13_polish_v2'])return;
 $id=28;$raw=get_post_meta($id,'_elementor_data',true);$data=json_decode($raw,true);if(!is_array($data))wp_send_json_error(['message'=>'Elementor data missing'],500);
 $logo='https://13xplay.upscaleera.com/wp-content/uploads/13xplay-assets/13xplay-logo.webp';
 $art='https://13xplay.upscaleera.com/wp-content/uploads/13xplay-assets/13xplay-hero.webp';
 $data=array_values(array_filter($data,fn($e)=>!in_array($e['id']??'',['13d00070','13d00090'],true)));
 x13walk($data,function(&$e)use($logo,$art){$eid=$e['id']??'';
  if(in_array($eid,['13d00003','13d00082'],true)){$e['widgetType']='image';$e['settings']=['image'=>['url'=>$logo,'id'=>''],'image_size'=>'full','css_classes'=>$eid==='13d00003'?'x13-ref-logo x13-v2-logo':'x13-footer-logo x13-v2-logo'];}
  if($eid==='13d00015'){$e['settings']['image']=['url'=>$art,'id'=>''];$e['settings']['image_size']='full';$e['settings']['css_classes']='x13-mobile-art x13-v2-mobile-art';}
  if($eid==='13d00040'){$e['settings']['background_image']=['url'=>'','id'=>''];$e['settings']['background_color']='transparent';$e['settings']['css_classes']='x13-hero-right x13-v2-art-col';}
  if($eid==='13d00041'){$e['widgetType']='image';$e['settings']=['image'=>['url'=>$art,'id'=>''],'image_size'=>'full','css_classes'=>'x13-phone-widget x13-v2-art'];}
  if($eid==='13d00034'){$e['widgetType']='heading';$e['settings']=['title'=>'10%<br><small>EXTRA</small><span>BONUS</span>','header_size'=>'div','align'=>'center','title_color'=>'#FFD83D','typography_typography'=>'custom','typography_font_family'=>'Arial','typography_font_size'=>['unit'=>'px','size'=>58,'sizes'=>[]],'typography_font_weight'=>'900','css_classes'=>'x13-bonus-card x13-v2-bonus'];}
  if($eid==='13d00035'){$e['settings']['selected_icon']=['value'=>'fab fa-whatsapp','library'=>'fa-brands'];$e['settings']['icon_align']='left';$e['settings']['icon_indent']=['unit'=>'px','size'=>12,'sizes'=>[]];$e['settings']['text']='WHATSAPP NOW  ›';}
  if(in_array($eid,['13d00009','13d00075','13d00088'],true)){$e['settings']['selected_icon']=['value'=>'fab fa-whatsapp','library'=>'fa-brands'];$e['settings']['icon_align']='left';$e['settings']['icon_indent']=['unit'=>'px','size'=>8,'sizes'=>[]];}
  if($eid==='13d00083'){$e['settings']['editor']='<p>Fast ID. Secure support. Simple WhatsApp assistance.</p><p>© 2026 13XPLAY. All rights reserved.</p>';}
  $map=['13d00052'=>['fas fa-bolt','INSTANT','WITHDRAWAL'],'13d00054'=>['fas fa-headset','24X7','CUSTOMER SUPPORT'],'13d00056'=>['fas fa-lock','SECURE','TRANSACTIONS'],'13d00058'=>['fas fa-trophy','BEST ODDS','& BIG WINS']];
  if(isset($map[$eid])){[$ic,$t,$d]=$map[$eid];$e['settings']['selected_icon']=['value'=>$ic,'library'=>'fa-solid'];$e['settings']['title_text']=$t;$e['settings']['description_text']=$d;}
 });
 foreach($data as &$root){if(($root['id']??'')==='13d00050'&&isset($root['elements'])){$root['elements']=array_values(array_filter($root['elements'],fn($c)=>($c['id']??'')!=='13d00059'));foreach($root['elements'] as &$c){$c['settings']['_column_size']=25;$c['settings']['_inline_size']=25;}unset($c);$root['settings']['css_classes']='x13-benefit-strip x13-v2-bottom-strip';}}unset($root);
 x13walk($data,function(&$e){if(($e['id']??'')==='13d00007'&&isset($e['elements'])){$exists=false;foreach($e['elements'] as $w){if(($w['id']??'')==='13v2ready')$exists=true;}if(!$exists){$ready=['id'=>'13v2ready','elType'=>'widget','widgetType'=>'heading','isInner'=>false,'settings'=>['title'=>'READY TO WIN BIG?<br>JOIN <span>13XPLAY</span> NOW!','header_size'=>'div','align'=>'center','align_mobile'=>'center','title_color'=>'#FFFFFF','typography_typography'=>'custom','typography_font_family'=>'Arial','typography_font_size'=>['unit'=>'px','size'=>25,'sizes'=>[]],'typography_font_size_mobile'=>['unit'=>'px','size'=>23,'sizes'=>[]],'typography_font_weight'=>'900','css_classes'=>'x13-v2-ready'],'elements'=>[]];$out=[];foreach($e['elements'] as $w){if(($w['id']??'')==='13d00011')$out[]=$ready;$out[]=$w;}$e['elements']=$out;}}});
 $css=<<<'CSS'
<style id="x13-v2-overrides">
:root{--xg:#31f46a;--xt:#14dcb1;--xgold:#ffd83d}body.elementor-page-28{background:#010303!important}.x13-ref-header{background:#010303!important;border-bottom:1px solid rgba(49,244,106,.35)!important}.x13-v2-logo img{width:270px!important;max-height:72px!important;object-fit:contain!important}.x13-ref-hero:before{background:linear-gradient(90deg,rgba(0,2,2,.98),rgba(0,2,2,.90) 44%,rgba(0,2,2,.22) 72%,rgba(0,2,2,.60)),radial-gradient(circle at 78% 43%,rgba(49,244,106,.18),transparent 32%)!important}.x13-main-title .elementor-heading-title{font-size:94px!important;line-height:.89!important}.x13-main-title .elementor-heading-title span{color:var(--xg)!important;font-size:1.16em}.x13-subtitle p{font-size:23px!important}.x13-v2-art-col{min-height:720px!important;background:none!important;filter:none!important;overflow:visible!important}.x13-v2-art-col:before{display:none!important}.x13-v2-art-col>.elementor-widget-wrap{padding:0!important;align-content:center!important}.x13-v2-art img{width:100%!important;max-height:720px!important;object-fit:contain!important;filter:drop-shadow(0 18px 30px rgba(0,0,0,.6)) drop-shadow(0 0 30px rgba(49,244,106,.16))}.x13-v2-bonus>.elementor-widget-container{width:205px;height:205px;border-radius:50%;display:grid;place-items:center;margin:-225px 0 28px auto!important;background:radial-gradient(circle,#171300,#070600 65%);border:8px double var(--xgold);box-shadow:0 0 0 4px #66510b,0 0 30px rgba(255,216,61,.25);position:relative;z-index:4}.x13-v2-bonus .elementor-heading-title{color:var(--xgold)!important;line-height:.78!important;font-family:Arial Black,Arial,sans-serif!important;text-shadow:0 0 16px rgba(255,216,61,.25)}.x13-v2-bonus small{font-size:.35em}.x13-v2-bonus span{display:block;font-size:.30em;color:#fff;background:linear-gradient(#26dc58,#087d2e);padding:8px 14px;border-radius:99px;margin-top:12px;transform:rotate(-3deg);text-shadow:none}.x13-main-whatsapp .elementor-button{font-size:35px!important;border-radius:38px!important;border:3px solid #baff96!important;padding:22px 24px!important;background:linear-gradient(#21dc3e,#019525)!important}.x13-v2-ready{margin-top:22px!important}.x13-v2-ready .elementor-heading-title{font-family:Arial Black,Arial,sans-serif!important;font-style:italic!important;line-height:1.14!important}.x13-v2-ready span{color:var(--xg)}.x13-v2-bottom-strip{background:#020505!important}.x13-v2-bottom-strip>.elementor-container{max-width:1050px!important}.x13-v2-bottom-strip .x13-feature-card>.elementor-widget-container{border:0!important;border-radius:0!important;background:transparent!important;min-height:75px!important}.x13-support-section{display:none!important}.x13-ref-copyright{display:none!important}.x13-ref-footer{padding-top:36px!important}.x13-footer-logo img{width:230px!important}.x13-mobile-art{display:none!important}
@media(max-width:767px){.x13-ref-header>.elementor-container{display:flex!important;flex-wrap:nowrap!important}.x13-logo-col{width:48%!important}.x13-nav-col,.x13-trust-col{display:none!important}.x13-header-btn-col{width:52%!important}.x13-ref-header-cta .elementor-button{font-size:11px!important;padding:11px 8px!important}.x13-v2-logo img{width:170px!important}.x13-ref-hero>.elementor-container{display:block!important}.x13-hero-left,.x13-v2-art-col{width:100%!important}.x13-kicker p{text-align:center!important;font-size:12px!important}.x13-main-title .elementor-heading-title{text-align:left!important;font-size:58px!important;line-height:.88!important}.x13-subtitle p{text-align:left!important;font-size:15px!important;margin:8px 0 8px!important}.x13-mobile-art{display:block!important;margin:0 0 8px!important}.x13-mobile-art img{height:auto!important;max-height:450px!important;object-fit:contain!important;border-radius:0!important;filter:drop-shadow(0 0 25px rgba(49,244,106,.15))!important}.x13-v2-art-col{display:none!important}.x13-feature-row{display:none!important}.x13-offer-row>.elementor-container{display:block!important}.x13-offer-row .elementor-column{width:100%!important}.x13-id-card>.elementor-widget-container{min-height:108px!important}.x13-v2-bonus>.elementor-widget-container{width:185px;height:185px;margin:12px auto 0!important}.x13-v2-ready .elementor-heading-title{font-size:23px!important}.x13-main-whatsapp .elementor-button{font-size:28px!important;padding:20px 10px!important;border-radius:34px!important}.x13-safe-note p{font-size:10px!important}.x13-v2-bottom-strip>.elementor-container{display:flex!important;flex-wrap:wrap!important}.x13-v2-bottom-strip .elementor-column{width:50%!important}.x13-v2-bottom-strip .x13-feature-card>.elementor-widget-container{min-height:70px!important;padding:10px 6px!important}.x13-ref-footer>.elementor-container{display:block!important}.x13-ref-footer .elementor-column{width:100%!important;margin-bottom:18px}.x13-ref-footer p{text-align:center!important}.x13-footer-logo img{width:190px!important;margin:auto!important}.x13-footer-btn .elementor-button{width:100%!important}}
</style>
CSS;
 x13walk($data,function(&$e)use($css){if(($e['id']??'')==='13d00099'&&($e['widgetType']??'')==='html'){$e['settings']['html']=preg_replace('#<style id="x13-v2-overrides">.*?</style>#s','',$e['settings']['html']??'').$css;}});
 update_post_meta($id,'_elementor_data',wp_slash(wp_json_encode($data)));update_post_meta($id,'_x13_layout_version','reference-layout-v2');delete_post_meta($id,'_elementor_css');delete_post_meta($id,'_elementor_element_cache');clean_post_cache($id);if(class_exists('\\Elementor\\Plugin')&&isset(\Elementor\Plugin::$instance->files_manager)){\Elementor\Plugin::$instance->files_manager->clear_cache();}do_action('litespeed_purge_all');
 wp_send_json(['ok'=>true,'post_id'=>$id,'layout_version'=>'reference-layout-v2','root_elements'=>count($data),'logo'=>$logo,'hero_art'=>$art]);
},1);
